### PR TITLE
Add `quickCheckGen` and variants

### LINKED ISSUE #47: Add `forAll`
From `Test.QuickCheck`:

``` haskell
forAll :: (Show a, Testable prop) => Gen a -> (a -> prop) -> Property
```

Essentially, this allows you to write quickCheck tests without relying on an `Arbitrary` instance for all of the arguments you need. This would help us avoid the problem of orphan Arbitrary instances. For instance:

``` purescript
quickCheck $ forAll (maps :: Gen (Map Int String))
                    (\m -> m == Map.fromUnfoldable (Map.toFoldable m))
```

or something. Then, we are free to put `Gen` values for any type anywhere, without all the `newtype` shenanigans. We can also freely parameterize `Gen` values based on other values that are only available at runtime, etc etc. I'm sure I've complained about these aspects of type classes before. ;)

### PR DESCRIPTION
**Pull request by garyb**
Resolves #47 

The formulation here is a little different though, as you don't actually need to split the generator and test the way that was suggested in the issue, since you can write it in the generator directly:

``` purescript
forAll do
  m <- maps :: Gen (Map Int String))
  pure $ m == Map.fromUnfoldable (Map.toFoldable m)
```

Since that issue was opened, `MonadGen` has come into existence, and with it I've given up using `Arbitrary` at all, the only problem is you can't throw `MonadGen` constrained things directly into `quickcheck`, as it doesn't know what to instantiate the `MonadGen m` with. These `forAll` varieties solve that.

/cc @hdgarrood

### CODE REVIEW

**Comment by hdgarrood** [comment]
This looks great! My only quibble is that I don't think the name `forAll` really makes sense any more with this formulation.

**Comment by garyb** [comment]
Yeah, I guess you're right there actually :smile: 

Any thoughts on a better name?

**Comment by hdgarrood** [comment]
Not really... `quickCheckGen`?:confused:

**Comment by matthewleon** [comment]
Is this not solvable more idiomatically by writing an appropriate `Testable` instance?

`(MonadGen m, Testable prop) => Testable (m prop)`

**Comment by matthewleon** [comment]
Ah, I see the problem with what I've written above. It has to be something more like

`Testable prop => Testable (forall m. MonadGen m => m prop)`

**Comment by matthewleon** [comment]
> Not really... quickCheckGen?

I like this. It makes it reasonably clear what the function does in relation to the others.

**Comment by garyb** [comment]
I actually was thinking about this again today, had forgotten about the suggestion here and thought up the same name (or so I thought). I think it's a good option, will update accordingly.

**Pull request merged**
