### PR TITLE
ensure Gen seed is modified after resize

### PR DESCRIPTION
**Pull request by matthewleon**
see https://github.com/purescript/purescript-gen/issues/12#issuecomment-368525522

@safareli you might want to give this a quick check (totally accidental pun) to see if I've missed anything.

### CODE REVIEW

**Comment by garyb** [comment]
A minor thing, but this could probably be written nicely in terms of `state`.

**Comment by matthewleon** [comment]
> A minor thing, but this could probably be written nicely in terms of state.

Cool, I'll give it a shot.

**Comment by matthewleon** [comment]
@garyb that is indeed much more elegant. Should be good now.

**Comment by garyb** [comment]
Thanks!

**Pull request merged**
