### PR TITLE
Support version of quickcheck where generator size can be set

### PR DESCRIPTION
**Pull request by vanHavel**
At the moment random generators used in quickcheck are created with a default size of 10. This is not very flexible and that magic number is not documented. I propose to add a new, most general variant of the quickcheck function that allows to set the size of the generator.

### CODE REVIEW

**Comment by garyb** [comment]
Do you think maybe just using `resize` for the property would be simpler instead? (Just thinking, there's like 8 different versions of the `quickCheck` function we could provide to cover every permutation of size/seed/purity, which seems a little silly when size at least can be set "internally").

**Comment by vanHavel** [comment]
Can you explain how to use `resize` on the property? Say I want to test a property of lists of size 100. The workaround I came up with so far is
- create newtype wrapper List100 for lists
- define new Arbitrary instance for List100 by using `resize 100`

Is there an easier solution?

One way to reduce the number of versions of `quickCheck` would be to remove the `quickCheckWithSeed` function and have only one function with full control over the generator state. But that change would not be backwards-compatible.

**Comment by garyb** [comment]
I was thinking along the lines of:

``` purescript
  quickCheck do
    xs :: Array Int <- resize 100 arbitrary
    pure $ length xs <= 100
```

(You also wouldn't necessarily need the type annotation on `xs` if the test was less trivial)

**Comment by vanHavel** [comment]
That seems like a reasonable workaround. I think it might be a good idea to add this example as a test case and mention the standard generator size of 10 in the documentation.

**Pull request closed without merging**
