### PR TITLE
Stack safe gen

### PR DESCRIPTION
**Pull request by hdgarrood**
I am not sure if the dependency on `purescript-free` is acceptable, but this does work, so at least is a good starting point. The test fails with the current master code, and passes after applying the second commit in this PR.

### CODE REVIEW

**Comment by garyb** [comment]
I think adding a `free` dependency is probably fine, they're both in a similar position in the current dependency hierarchy:

graph1 dot

**Comment by garyb** [comment]
Unless there's something we can do with `tailrec` instead perhaps?

**Comment by hdgarrood** [comment]
Ah, yes, depending on `tailrec` only adds `tailrec` itself and `identity`; `free` adds 9 extra dependencies (including itself).

**Comment by jdegoes** [comment]
That would be better, since this one is not stack safe in all cases. :smiling_imp:

**Comment by hdgarrood** [comment]
Sorry, I don't follow. Is that a problem with my code here or a problem with Trampoline itself?

**Comment by jdegoes** [comment]
Any place in which creating and running a state occurs in recursive position will blow the stack for sufficiently deep recursion; this formulation of `Gen` has the same problem as `StateT s Trampoline`, which is not stack safe in general. What you want here is `MealyT` from purescript-machines (which is what StrongCheck uses), but I think it'd be better to just use MonadRec, fewer dependencies and more in keeping with the light theme of quickcheck.

**Comment by hdgarrood** [comment]
I had a go with tailrec but it's horrendously slow and still not stack safe. Any pointers?

**Comment by jdegoes** [comment]
> I had a go with tailrec but it's horrendously slow and still not stack safe. Any pointers?

I don't think any large-scale examples have used `MonadRec`. I think what you have to do is build some (unfoldable) structure which will be run "at the end of the world" using `MonadRec`; if you try to call `tailRec` inside the implementations of your functions, you won't actually achieve whole-system stack safety. `tailRec` has to be pushed up to the top of the program, which means you need to be composing unfoldable-like things which can later be run using `tailRec`.

The alternative is something like StrongCheck's `Gen`, which is stack-safe because it's built on `MealyT`, which is at least equivalent (if not identical) to a stack-safe (trampolinable) `StateT`.

**Comment by paf31** [comment]
Tailrec has some performance issues when the instance involves tupling arguments, because instances use records, I think. It should be possible to speed up some of the instances by using `Tuple` or multiple arguments instead.

**Comment by garyb** [comment]
Should I wait for some version of this before releasing a new version, or should I just do it now?

**Comment by hdgarrood** [comment]
I'm going to have another stab at this over the next few hours - how about if we wait a little bit for now, but if I haven't managed anything by tomorrow, just go ahead?

**Comment by garyb** [comment]
Sounds good :+1:

**Comment by hdgarrood** [comment]
Closed in favour of #37 / #38.

**Pull request closed without merging**
