### PR TITLE
Use Number type to avoid overflows in lcgNext

### PR DESCRIPTION
**Pull request by paf31**
@garyb Does this look ok? Did you have any tests to verify this?

### CODE REVIEW

**Comment by paf31** [comment]
@garyb Any thoughts on this?

**Comment by garyb** [comment]
Oh, sorry! Forgot about/missed this one.

I don't have an explicit test, but I'd suggest `lcgNext 2 == 59559187`. I think pre-fix it will be `-1014182637`?

**Comment by garyb** [comment]
Maybe that's a test actually, `forall n. lcgNext n >= 0`.

**Comment by paf31** [comment]
`quickCheckPure 10 100 $ \x -> x < 0 || lcgNext x > 0` seems to work fine. I'll add proper tests later when I get round to writing test suites for things, but for now, this seems good enough to fix the immediate issue.

**Comment by paf31** [comment]
On a related note, you can now run QuickCheck tests directly inside `psci`, which is quite nice.

**Pull request merged**
