### PR TITLE
Include upper boundery in chooseInt, fixes #31

### LINKED ISSUE #31: `oneOf` and `elements` never yield the last element
Currently, `oneOf` is implemented as
```purescript
oneOf :: forall a. Gen a -> Array (Gen a) -> Gen a
oneOf x xs = do
  n <- chooseInt zero (length xs)
  if n < one then x else fromMaybe x (xs !! (n - one))
```
Apparently, `chooseInt a b` returns a random integer from the set `a, a + 1, ..., b - 1`, excluding the value `b`. Consequently, the maximum value for the index `n - one` in the last line is `length xs - 2` and the last element of `xs` will never be chosen:

``` purescript
> showSample (oneOf (pure 1) [pure 2])
[1,1,1,1,1,1,1,1,1,1]
```

The same is true for `elements`.

### PR DESCRIPTION
**Pull request by sharkdp**
For details, see #31

### CODE REVIEW

**Comment by garyb** [comment]
:+1: 

I guess we should fix the comment in `purescript-random` too, either that or fix the behaviour there.

**Comment by sharkdp** [comment]
> I guess we should fix the comment in purescript-random too, either that or fix the behaviour there.

Which comment? Are you referring to the differences in behavior between `Control.Monad.Eff.Random.randomInt` and `Test.QuickCheck.Gen.chooseInt`? I added a short explanation in the documentation.

**Comment by garyb** [comment]
Sorry, I wasn't quite with it when I wrote that comment :)

But yeah, in that case, I wonder if it would be better to change QC's `randomInt` behaviour to return the full range of values instead? I'm not sure, it's probably fine either way as it's documented now.

**Comment by garyb** [comment]
Actually, I think we probably should change `chooseInt` here to be able to return the max value too (sorry)

**Comment by sharkdp** [comment]
@garyb This is the better solution, I agree. I was afraid of proposing a breaking change.

I updated the PR now to change the behavior of `chooseInt`.

`chooseInt` is also used in `arrayOf` and `arrayOf1`, but as far as I can tell, the intention there was to have include the upper boundary, so I hope this is fine.

**Comment by garyb** [comment]
I think it's a fix more than a breaking change, given the way `randomInt` was being used in `oneOf` and the other use cases you mentioned it looks like we already expected it to return the whole range.

:+1:

**Pull request merged**
