### PR TITLE
Fix issue with instance selection in PSCi.

### PR DESCRIPTION
**Pull request by paf31**
/cc @garyb 

This allows us to run `quickCheck` (instead of `quickCheckPure`) in PSCi, where previously it failed because the compiler wouldn't find a `Monad` instance for the uninstantiated `forall`. That's still a bug in the compiler, but I think this is nicer anyway.

### CODE REVIEW

**Comment by garyb** [comment]
Ehh yes, I probably did that when I didn't know what I was doing, as I would tend to have put `eff` in the type these days too!

This is most likely a breaking change though, so will need a version bump.

**Comment by paf31** [comment]
Yep, I'll release a major version after merging. Does this have any dependencies in core?

**Comment by paf31** [comment]
Uh, reverse-dependencies, I mean.

**Comment by garyb** [comment]
I don't know off the top of my head, I can check in a minute. I don't think so, but possibly - it would have to be far along the dependency graph it does, so there won't be many.

**Comment by garyb** [comment]
- [ ] purescript-maps
- [ ] purescript-sets
- [ ] purescript-graphs

**Comment by paf31** [comment]
Thanks!

**Pull request merged**
