### PR TITLE
Add `MonadGen` instance

### PR DESCRIPTION
**Pull request by garyb**

### CODE REVIEW

**Comment by paf31** [comment]
Will QC continue to provide the same functions (`elements`, `frequency`, etc.)? I assume this will be a major version bump anyway.

Actually, we should probably merge #63 and possibly #69 while we're at it.

**Comment by garyb** [comment]
I don't think it needs to be a major version bump - there are no new dependencies (`-gen`'s dependencies are a subset of `-quickcheck`'s, and there are no changes to the interface).

Updating things to re-export from `Gen` is fine by me, I figured I'd make this change about as unobtrusive as I could, as it's just so quickcheck can be used with things written for `MonadGen`.

**Comment by paf31** [comment]
👍 Seems good to me then. No real harm in a major bump actually, since everyone will only just be getting round to updating now anyway.

**Comment by paf31** [comment]
Shall we merge this one?

**Pull request merged**
